---
- name: copy daemon.sh (CATALINA_OUT & JAVA_OPTS)
  template:
    src: daemon.sh.j2
    dest: "{{ item }}/bin/daemon.sh"
    mode: 0755
    owner: tomcat
    group: tomcat
  with_items: "{{ CATALINA_HOME }}"
  when: item != ""