---
- name: ipset installed or not
  command: /usr/sbin/service ipset status
  register: ipset_result
  ignore_errors: yes

- name: ipset installed or not
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_result is failed
  ignore_errors: yes

- name: ipset ping rules check
  command: /usr/sbin/ipset list ping
  register: ipset_ping
  ignore_errors: yes

- name: create ping group if not exist
  command: /usr/sbin/ipset create ping hash:net
  when: ipset_ping is failed

- name: ipset add ip to ping
  command: /usr/sbin/ipset add ping "{{ item }}"
  with_items: "{{ ping_add }}"
  ignore_errors: yes

- name: ipset del ip from ping
  command: /usr/sbin/ipset del ping "{{ item }}"
  with_items: "{{ ping_del }}"
  ignore_errors: yes

- name: ipset save
  command: /usr/sbin/service ipset save

- service:
    name: ipset
    state: restarted