---
- hosts: "{{ host }}"
  gather_facts: yes
  become: yes

  roles:
    - jdk7u79_install
    - rng-tools_install
    - tomcat_apr_install
    - nginx_install
    - tomcat_service_install
    - tomcat_daemon_setup
    - rsync_conf_sync
    - initialization_folder
    - log_rotate_single
    - font_install