---
- name: sync rsyncd.conf
  template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    mode: 0644

- name: sync rsyncd.secrets
  copy:
    src: rsyncd.secrets
    dest: /etc/rsyncd.secrets
    mode: 0600

- name: rsyncd start
  command: rsync --daemon --config=/etc/rsyncd.conf