---
- name: ipset installed or not
  command: /usr/sbin/service ipset status
  register: ipset_result
  ignore_errors: yes

- name: ipset installed or not
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_result is failed
  ignore_errors: yes

- name: ipset cdn_nginx rules check
  command: /usr/sbin/ipset list cdn_nginx
  register: ipset_cdn_nginx
  ignore_errors: yes

- name: create cdn_nginx group if not exist
  command: /usr/sbin/ipset create cdn_nginx hash:net
  when: ipset_cdn_nginx is failed

- name: ipset add ip to cdn_nginx
  command: /usr/sbin/ipset add cdn_nginx "{{ item }}"
  with_items: "{{ cdn_nginx_add }}"
  ignore_errors: yes

- name: ipset del ip from cdn_nginx
  command: /usr/sbin/ipset del cdn_nginx "{{ item }}"
  with_items: "{{ cdn_nginx_del }}"
  ignore_errors: yes

- name: ipset save
  command: /usr/sbin/service ipset save

- service:
    name: ipset
    state: restarted