---
- name: ipset installed or not
  command: /usr/sbin/service ipset status
  register: ipset_result
  ignore_errors: yes

- name: ipset installed or not
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_result is failed
  ignore_errors: yes

- name: ipset desktop_cloud rules check
  command: /usr/sbin/ipset list desktop_cloud
  register: ipset_desktop_cloud
  ignore_errors: yes

- name: create desktop_cloud group if not exist
  command: /usr/sbin/ipset create desktop_cloud hash:net
  when: ipset_desktop_cloud is failed

- name: ipset add ip to desktop_cloud
  command: /usr/sbin/ipset add desktop_cloud "{{ item }}"
  with_items: "{{ desktop_cloud_add }}"
  ignore_errors: yes

- name: ipset del ip from desktop_cloud
  command: /usr/sbin/ipset del desktop_cloud "{{ item }}"
  with_items: "{{ desktop_cloud_del }}"
  ignore_errors: yes

- name: ipset save
  command: /usr/sbin/service ipset save

- service:
    name: ipset
    state: restarted