---
- name: ipset installed or not
  command: /usr/sbin/service ipset status
  register: ipset_check
  ignore_errors: yes

- name: ipset install
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_check is failed
  ignore_errors: yes

- name: ipset group rules check
  command: /usr/sbin/ipset list desktop_cloud
  register: ipset_g
  ignore_errors: yes

- name: ipset create group
  command: /usr/sbin/ipset create desktop_cloud hash:net
  when: ipset_g is failed

- name: ipset add ip to group desktop_cloud
  command: /usr/sbin/ipset add desktop_cloud "{{ item }}"
  with_items: "{{ ipset_service.desktop_cloud }}"
  ignore_errors: yes
  
- name: ipset save
  command: /usr/sbin/service ipset save

- service:
    name: ipset
    state: restarted

