---
#- name: copy tomcat management script template part to "{{ host }}"
#  template: src=tomcat-initd-template.sh dest=/etc/init.d/{{ initd_file }} mode=755
#  register: conf_changed
#
#- name: copy tomcat management script file part to "{{ host }}"
#  copy: src=tomcat dest=/etc/init.d/tomcat mode=755
#
#- name: centos7 daemon-reload
##  become: yes
#  command: "/usr/bin/systemctl daemon-reload"
#  when: ansible_distribution_version | version_compare('7', '>') and conf_changed|succeeded

- name: get "{{ host }}" old pid
  shell: /etc/init.d/"{{ item }}" statues
  with_items: "{{ initd_files }}"

- name: restart "{{ host }}" tomcat
#  become: yes
  service: name="{{ item }}" state=restarted
  with_items: "{{ initd_files }}"

- name: get "{{ host }}" new pid
  shell: /etc/init.d/"{{ item }}" statues
  with_items: "{{ initd_files }}"


