---
- name: yum install essential packages, if not, copy module will not work
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python

- name: copy tomcat management script template part to "{{ host }}"
  template:
    src: tomcat-jdk7u79.sh
    dest: "/etc/init.d/{{ initd_file }}"
    mode: 0755

- name: make tomcat start on boot
  service:
    name: "{{ initd_file }}"
    enabled: yes