---
- name: statement v_date
  command: date +%y%m%d%H%M%S
  register: v_date

- name: Backup ipset
  command: cp /etc/sysconfig/ipset /tmp/ipset_{{ v_date.stdout }}
  ignore_errors: yes
  
- name: ipset installed or not
  command: service ipset status
  register: ipset_check
  ignore_errors: yes

- name: ipset install
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_check.stderr != ""
  ignore_errors: yes

- name: ipset group rules check
  command: ipset list pt_sunrise
  register: ipset_g
  ignore_errors: yes

- name: ipset create group pt-sunrise
  command: ipset create pt_sunrise hash:net
  when: ipset_g.stderr != ""

- name: ipset add ip to group pt-sunrise
  command: ipset add pt_sunrise "{{ item }}"
  with_items: "{{ pt_sunrise }}"
  ignore_errors: yes

- name: ipset save
  command: service ipset save

- service:
    name: ipset
    state: restarted
