---
- name: ipset installed or not
  command: /usr/sbin/service ipset status
  register: ipset_result
  ignore_errors: yes

- name: ipset installed or not
  yum: name={{ item }} state=present
  with_items:
    - ipset
    - ipset-service
  when: ipset_result is failed
  ignore_errors: yes

- name: ipset pcb rules check
  command: /usr/sbin/ipset list pcb
  register: ipset_cdn
  ignore_errors: yes

- name: create pcb group if not exist
  command: /usr/sbin/ipset create pcb hash:net
  when: ipset_cdn is failed

- name: ipset add ip to pcb
  command: /usr/sbin/ipset add pcb "{{ item }}"
  with_items: "{{ pcb_add }}"
  ignore_errors: yes

- name: ipset del ip from pcb
  command: /usr/sbin/ipset del pcb "{{ item }}"
  with_items: "{{ pcb_del }}"
  ignore_errors: yes

- name: ipset save
  command: /usr/sbin/service ipset save

- service:
    name: ipset
    state: restarted