---
- name: restart service  , in all cases, also issue daemon-reload to pick up config changes
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items: "{{ operation }}"